version: '2'
services:
  db:
    image: 'postgres:14'
    container_name: 'db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=esempla'
    ports:
      - 5432:5432
  app:
    container_name: 'esemplacontainer'
    build: .
    image: 'esempla:v1'
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/esempla
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APPLICATION_MINIO_BUCKET_NAME=test
      - APPLICATION_MINIO_ACCESS_KEY=minioadmin
      - APPLICATION_MINIO_ACCESS_SECRET=minioamin
      - APPLICATION_MINIO_ACCESS_URL=http://127.0.0.1:9000